### ISSUE TITLE
Must use typescript grammar to ensure GitHub compatibility 

### ISSUE THREAD

**Issue by evoactivity** [edge-js/edge-vscode#2]
### Package version

1.5.0

### Describe the bug

I am working on getting GitHub support for highlighting edge files. GitHub uses the atom javascript textmate grammar which does not include `#expression` in it's repository causing the highlighting to be broken for highlighting powered by atom's javascript grammar.

You can see how github will highlight edge files using this preview app which also used the atom javascript grammar.
[Nova Lightshow JS preview](https://novalightshow.netlify.app/?grammar-type=url&grammar=https%3A%2F%2Fraw.githubusercontent.com%2Fedge-js%2Fedge-vscode%2Fmain%2Fsyntaxes%2Fedge.tmLanguage.json&sample-type=url&sample=https%3A%2F%2Fraw.githubusercontent.com%2Fedge-js%2Fedge%2Fdevelop%2Fexamples%2Fviews%2Fwelcome.edge)
<img width="777" alt="image" src="https://github.com/edge-js/edge-vscode/assets/83799/bdfce8ac-d65c-42b4-a328-3cf93e42f1fc">

This is how it highlights using source.ts instead
[Nova Lightshow TS preview](https://novalightshow.netlify.app/?grammar-type=url&grammar=https%3A%2F%2Fraw.githubusercontent.com%2Fevoactivity%2Fedge-vscode%2Fuse-typescript-grammar-include%2Fsyntaxes%2Fedge.tmLanguage.json&sample-type=url&sample=https%3A%2F%2Fraw.githubusercontent.com%2Fedge-js%2Fedge%2Fdevelop%2Fexamples%2Fviews%2Fwelcome.edge)
<img width="753" alt="image" src="https://github.com/edge-js/edge-vscode/assets/83799/5fa0d1ca-b0ea-48d6-9085-b0f94aacf792">

**Comment by thetutlage** [comment]
Okay, if I get it right. We have to switch from `source.js` to `source.ts` and everything will work fine?

Does this change has to be made within this repo? Or can we just use `source.ts` inside the source code shared with Github linguist?

**Comment by evoactivity** [comment]
It must be made in this repo. Linguist uses this repository as a submodule to pull in the grammar so it will be automatically updated as changes are made to the grammar without us needing to submit patches back to linguist.

**Comment by thetutlage** [comment]
Cool. Makes sense
