### ISSUE TITLE
Strange auto-format behavior on save

### ISSUE THREAD

**Issue by DimitriDe** [edge-js/edge-vscode#4]
### Package version

1.5.0

### Describe the bug

Using a component in a edge view, I send properties like this including some html as string for the label (not a good practice but it's for demonstration purpose) :
```
@!component('components/inputs/checkbox', {
  label: 'J\'accepte les <a class="font-medium text-primary-600 hover:underline dark:text-primary-500" href="/terms" target="_blank">Conditions générales</a>',
  name: 'terms',
  className: 'my-3',
  required: true
})
```
On save (not related to prettier or eslint) the extension seems to want to save horizontal space and cuts the string like this :
```
@!component('components/inputs/checkbox', {
label: 'J\'accepte les <a class="font-medium text-primary-600 hover:underline dark:text-primary-500" href="/terms"
  target="_blank">Conditions générales</a>',
name: 'terms',
className: 'my-3',
required: true
})
```
But the code is now broken and doesn't compile. The only way I found to prevent this is to disable or uninstall the extension.
Maybe I missed something and the auto-format could be disabled ?

**Comment by Julien-R44** [comment]
Hey

Add this to your vscode configuration : 

```json
"[edge]": {
  "editor.formatOnSave": false
}
  ```
